[package]
name = "tls_fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1.6.0" }
tokio = { version = "1.37.0", features = ["full"] }
hyper = { version = "1.3.1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1.3", features = ["full"] }
